### ISSUE TITLE
Ambiguous error

### ISSUE THREAD

**Issue by julianduque** [brycebaril/client-request#12]
If I set 

```
const options = {
  url: "http://example.com"
}
request(options, callback)
```

it fails with (from url.parse):

```
TypeError: Parameter "url" must be a string, not undefined
```

Which is a little bit confusing at the beginning (if you don't read the docs 😛)

Do you think it can support `options.uri || options.url` to avoid confusions?

**Comment by brycebaril** [comment]
I can't remember the exact reason I didn't support both, possibly trying to emulate how another library works... either way it doesn't seem that important anymore, I'd definitely consider a PR that added the `url` alias to `options` ;P
