### ISSUE TITLE
browser support?

### ISSUE THREAD

**Issue by jasonkarns** [brycebaril/client-request#2]
Is this es3 compatible? Does it fallback to XDR for IE8/9?

**Comment by brycebaril** [comment]
ES3 compatible: it's pretty close, upon a brief scan only saw one ES5 method.

However, it is not designed for the browser, typically to make it work with the browser I'd use [browserify](http://browserify.org/) which has its own mechanism for polyfilling the Node->Browser http client behavior, and has its own compatibility concerns.
